### ISSUE TITLE
Clarification and Enhancement Request for a Code Line and Readme Update

### ISSUE THREAD

**Issue by enum-class** [remytuyeras/aces#2]
I'm reviewing the codebase, specifically looking at a [particular line](https://github.com/remytuyeras/aces/blob/32de5a8ff73a5eed80a811b88f4677306ccad96b/aces.py#L289) in `generate_linear`, `generate_vanisher`, `generate_error`, and I'm unsure whether it's necessary to include % self.u before the return statement. 
```
return shift + b_res % self.u
```
Could you provide clarification on whether this addition is required for the intended functionality?

Additionally, I noticed the use of "Cyphertext" in the Readme. It seems there might be a typo, and the correct term should be "ciphertext."

Thanks

**Comment by remytuyeras** [comment]
Hi,

The operation `% self.u` is technically only required for multiplications between polynomials.

In essence, applying the operation `% self.u` serves to reduce the degree of the input polynomial when it is greater than or equal to that of self.u. When performing additions between polynomials with degrees lower than that specified for `self.u`, the resulting polynomial will inherently have a degree lower than `self.u`. 

This means that there is no imperative need to employ `% self.u` in such cases (even though the math assumes it needs to be applied). The only reduction operation needed is on the coefficients, for which we should use `% self.intmod`.

Hope this helps

EDIT: The statement above holds because the leading coefficient of self.u is taken to be invertible in $\mathbb{Z}_q$ (specifically, in the code, it is equal to 1)

**Comment by remytuyeras** [comment]
Also thanks for the typo!

**Comment by enum-class** [comment]
Thanks @remytuyeras
